# головний CI сценарій
name: Docker CI with ReportPortal and Playwright

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.5-dind
        privileged: true
        options: >-
          --dns 8.8.8.8 --dns 8.8.4.4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start containers
        run: |
          docker-compose up -d --build
          sleep 60  # Give services time to start

      - name: Run Playwright tests in container
        run: |
          docker-compose exec -T playwright-tests npx playwright test

      - name: Stop all containers
        if: always()
        run: docker-compose down --volumes
